name: Run Tests

on:
  pull_request:
    branches: [develop, main]
    types: [opened, synchronize, reopened]

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v6
        with:
          fetch-depth: 0

      - name: Set up Node.js
        uses: actions/setup-node@v6
        with:
          node-version: 20

      - name: Enable Corepack
        run: corepack enable

      - name: Install dependencies
        env:
          YARN_ENABLE_HARDENED_MODE: "0"
        run: yarn install --no-immutable

      - name: Run tests with coverage
        run: yarn vitest run --coverage

      - name: Check package version matches tag
        run: yarn check-version
      

    #   - name: Upload coverage to Codecov
    #     uses: codecov/codecov-action@v5
    #     with:
    #       files: coverage/coverage-final.json
    #       token: ${{ secrets.CODECOV_TOKEN }}  # optional if public repo
